<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<meta name="author" content="zayka" >
<script type="text/javascript" src="js/jquery.js">
</script>
<script type="text/javascript" src="js/fileupload.js">
</script>
<style>
#imageuploder
{
	background-color:#fff;
	position:absolute;
	width:500px;
	height:420px;
text-align:center;	
	}
.text2{
	font-family:Georgia, "Times New Roman", Times, serif;
	font-weight:500;
	color:#333;
	font-size:24px;
	}	
.text3{
		font-family:Georgia, "Times New Roman", Times, serif;
	font-weight:500;
	color:#555;
	font-size:16px;

	}	
	
	#upload{
		margin-left:130px;
		width:230px;
		height:250px;
		border:dashed 2px #555;}
	
</style>
<style type="text/css">
.classname4 {
	-moz-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	box-shadow:inset 0px 1px 0px 0px #bbdaf7;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #79bbff), color-stop(1, #378de5) );
	background:-moz-linear-gradient( center top, #79bbff 5%, #378de5 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#79bbff', endColorstr='#378de5');
	background-color:#79bbff;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #84bbf3;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
cursor:pointer;
	text-shadow:1px 1px 0px #528ecc;
}.classname4:hover {
	cursor:pointer;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #378de5), color-stop(1, #79bbff) );
	background:-moz-linear-gradient( center top, #378de5 5%, #79bbff 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#378de5', endColorstr='#79bbff');
	background-color:#378de5;
}.classname4:active {
	position:relative;
	top:1px;
	cursor:pointer;

}
#fileField{ opacity:0;}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
</head>
<body>

<div id="imageuploder">
<span class="text2">Upload your Photo </span>
<div id="upload">

<span id="uploadmsg" class="text2" style=" color:#999;position:relative; top:100px;">Drag your image here</span>

</div>          
<div  class="classname4" style="width:50px; overflow:hidden; height:20px; margin-top:10px; ">
<span style="position:absolute; margin-left:-10px;">Or Select</span>
   <input type="file" id="fileField" name="fileField" style="margin-left:-30px; padding:40px 10px 10px 10px;margin-top:-10px;"/> 
</div>           
            


<div id="fileName" class="text3"></div>
<div id="fileSize" class="text3"></div>
<div id="fileType" class="text3"></div>
<div id="progressNumber" class="text3"></div>
 <script type="text/javascript" src="js/fileupload.js"></script>
</div>
</body>
</html>
